### ISSUE TITLE
Floating Ip Configuration

### ISSUE THREAD

**Issue by jawabuu** [costela/hcloud-ip-floater#28]
Hey @costela Is there additional configuration that one needs to make on the nodes before routing works correctly or does the hcloud-ip-floater 'just work'
The additional configuration in this case is assigning the floating ip to `eth0` for all the nodes

**Comment by costela** [comment]
hi @jawabuu 

The only current dependency is a component to assign IPs to services (like metallb). There was some work towards implementing this in `hcloud-ip-floater` itself to make it totally self-suficient, but then hetzner released their load balancer service and that took some wind off of hcloud-ip-floater's sails. :disappointed: 

Hope that helps a bit.

**Comment by jawabuu** [comment]
Thanks @costela `hcloud-ip-floater` is still extremely useful.
The biggest use case for me being a fixed registration ip for k3s HA.
How does it get around the requirement of configuring the ip on every single node?
e.g. `fip-controller` requires this.

**Comment by costela** [comment]
@jawabuu that's why you probably need `metallb`.
