### ISSUE TITLE
arm64 image

### ISSUE THREAD

**Issue by ghorofamike** [costela/hcloud-ip-floater#63]
will there be some ready made arm64 images? [CAX servers](https://www.hetzner.com/news/arm64-cloud)  are available in falkenstein or so.

**Comment by costela** [comment]
New release (v0.1.6) switched to multi-arch and should fix this. Please take it for a spin!
(note that the registry switched from dockerhub to ghcr)

**Comment by ghorofamike** [comment]
will give it a spin when i redeploy next.
