### ISSUE TITLE
Suitable for egress traffic?

### ISSUE THREAD

**Issue by jampy** [costela/hcloud-ip-floater#94]
I'm looking for a solution to direct **egress** traffic via a floating IP, no ingress traffic.

The reasoning is to connect to external services (like Amazon RDS) from a well-known public IP address in order to pass the firewall.

I'm not sure if hcloud-ip-floater is suitable for that or if it is meant for ingress traffic only?

Thanks.

**Comment by costela** [comment]
Caveat: haven't used this in a while, so I may be overlooking something :see_no_evil: 

I don't think this is doable out-of-the-box: the floating IP gets attached to the node, but the controller makes no changes to ensure outgoing pod traffic gets out of the node via the floating IP (as opposed to the default route) :face_with_diagonal_mouth:
